name: 'pittsburgh_weather'
version: '1.0.0'
config-version: 2

profile: 'weather'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pittsburgh_weather:
    +materialized: view
    +on_schema_change: "fail"
    
    staging:
      +materialized: view
      +tags: ["staging"]
    
    intermediate:
      +materialized: view
      +tags: ["intermediate"]
    
    marts:
      +materialized: table
      +tags: ["marts"]

tests:
  +store_failures: true
  +schema: dbt_test_failures

vars:
  weather_timezone: "America/New_York"