# https://docs.getdbt.com/docs/core/connect-data-platform/postgres-setup

weather:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: "{{ env_var('WEATHER_DB_USER') }}"
      password: "{{ env_var('WEATHER_DB_PASSWORD') }}"
      dbname: "{{ env_var('WEATHER_DB_NAME') }}"
      schema: weather_analytics
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default. 
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
