# Use the official Airflow image as the base
FROM apache/airflow:2.10.2

# Switch to airflow user for pip installations
USER airflow

# Copy and install Python requirements
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt