version: 2

models:
  - name: mart_current_conditions
    description: "Latest weather conditions for all NYC neighborhoods"
    columns:
      - name: neighborhood_name
        description: "Name of the neighborhood"
        data_tests:
          - not_null
      
      - name: last_updated
        description: "Timestamp of most recent observation"
        data_tests:
          - not_null
      
      - name: temp_fahrenheit
        description: "Current temperature in Fahrenheit"
      
      - name: weather_condition
        description: "Current weather condition (Rain, Snow, Clear, etc.)"
  
  - name: mart_neighborhood_weekly_summary
    description: "Weekly weather summaries by neighborhood"
    columns:
      - name: week_start_date
        description: "Start date of the week (Monday)"
        data_tests:
          - not_null
      
      - name: neighborhood_name
        description: "Name of the neighborhood"
        data_tests:
          - not_null
      
      - name: days_with_data
        description: "Number of days in the week with observations"
        data_tests:
          - not_null
  
  - name: mart_borough_comparison
    description: "Daily weather comparison across NYC boroughs"
    columns:
      - name: borough
        description: "NYC borough name"
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten']
      
      - name: observation_date
        description: "Date of observations"
        data_tests:
          - not_null
      
      - name: neighborhood_count
        description: "Number of neighborhoods in this borough with data"