#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create Airflow database and user
    CREATE DATABASE ${AIRFLOW_DB_NAME};
    CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB_NAME} TO ${AIRFLOW_DB_USER};
    
    -- Create Weather database and user
    CREATE DATABASE ${WEATHER_DB_NAME};
    CREATE USER ${WEATHER_DB_USER} WITH PASSWORD '${WEATHER_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${WEATHER_DB_NAME} TO ${WEATHER_DB_USER};
EOSQL

echo "✅ Created databases: ${AIRFLOW_DB_NAME}, ${WEATHER_DB_NAME}"