version: 2

models:
  - name: stg_current_weather
    description: "Cleaned and standardized current weather observations"
    columns:
      - name: weather_id
        description: "Unique identifier for weather observation"
        data_tests:
          - unique
          - not_null
      
      - name: location_id
        description: "Foreign key to location"
        data_tests:
          - not_null
      
      - name: observation_time_est
        description: "Observation timestamp in EST"
        data_tests:
          - not_null
      
      - name: temp_celsius
        description: "Temperature in Celsius"
        data_tests:
          - not_null
      
      - name: temp_fahrenheit
        description: "Temperature converted to Fahrenheit"
        data_tests:
          - not_null
      
      - name: weather_code
        description: "WMO weather code (0-99)"
        data_tests:
          - not_null
  
  - name: stg_locations
    description: "Cleaned NYC neighborhood location data"
    columns:
      - name: location_id
        description: "Unique identifier for location"
        data_tests:
          - unique
          - not_null
      
      - name: neighborhood_name
        description: "Name of the neighborhood"
        data_tests:
          - not_null
      
      - name: community_board
        description: "NYC community board identifier"
      
      - name: latitude
        description: "Latitude coordinate"
        data_tests:
          - not_null
      
      - name: longitude
        description: "Longitude coordinate"
        data_tests:
          - not_null