version: 2

sources:
  - name: weather
    description: "Raw weather data loaded by Airflow from Open-Meteo API"
    database: weather_db
    schema: weather
    tables:
      - name: dim_location
        description: "NYC neighborhoods with geographic coordinates"
        columns:
          - name: location_id
            description: "Primary key"
            data_tests:
              - unique
              - not_null
          
          - name: neighborhood_name
            description: "Name of NYC neighborhood"
            data_tests:
              - not_null
          
          - name: latitude
            description: "Latitude coordinate"
            data_tests:
              - not_null
          
          - name: longitude
            description: "Longitude coordinate"
            data_tests:
              - not_null
      
      - name: dim_date
        description: "Date dimension for time-based analysis"
        columns:
          - name: date_id
            description: "Primary key"
            data_tests:
              - unique
              - not_null
          
          - name: date
            description: "Calendar date"
            data_tests:
              - unique
              - not_null
      
      - name: fact_current_weather
        description: "Current weather observations for NYC neighborhoods"
        columns:
          - name: weather_id
            description: "Primary key"
            data_tests:
              - unique
              - not_null
          
          - name: location_id
            description: "Foreign key to dim_location"
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('weather', 'dim_location')
                    field: location_id
          
          - name: date_id
            description: "Foreign key to dim_date"
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('weather', 'dim_date')
                    field: date_id
          
          - name: observation_time
            description: "Timestamp of weather observation"
            data_tests:
              - not_null
      
      - name: fact_weather_history
        description: "Historical weather data for trend analysis"
        columns:
          - name: history_id
            description: "Primary key"
            data_tests:
              - unique
              - not_null